# action.yml
name: "Akash on Github Actions Dynamic SDL"
description: "Update the Akash SDL File with Dynamic Values"
inputs:
  REPLACEMENT_VALUES: # id of input
    description: "A JSON object of replacements to make"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install gomplate
      shell: bash
      run: |-
        curl -o /usr/local/bin/gomplate -sSL https://github.com/hairyhenderson/gomplate/releases/download/<version>/gomplate_<os>-<arch>
        chmod 755 /usr/local/bin/gomplate
        gomplate --help
